import os
import sys
import unittest
from datetime import datetime
from unittest.mock import Mock
# This testing class has been mostly generated by AI, with minor adjustments by me.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from backend.cache import RedisCache


class FakeRedis:
    """Mock Redis client for testing that mimics real Redis behavior."""
    def __init__(self, fail_on_operation=None):
        self.data = {}
        self.ttls = {}  # Track TTL for each key
        self.fail_on_operation = fail_on_operation  # Can be 'get', 'set', 'delete', 'ping'

    def ping(self):
        if self.fail_on_operation == 'ping':
            raise Exception("Ping failed")
        return True

    def setex(self, key, ttl, value):
        if self.fail_on_operation == 'set':
            raise Exception("Set failed")
        self.data[key] = value
        self.ttls[key] = ttl

    def get(self, key):
        if self.fail_on_operation == 'get':
            raise Exception("Get failed")
        return self.data.get(key)

    def delete(self, key):
        if self.fail_on_operation == 'delete':
            raise Exception("Delete failed")
        if key in self.data:
            self.data.pop(key, None)
            self.ttls.pop(key, None)
            return 1  # Return count of deleted keys (like real Redis)
        return 0


class RedisCacheTests(unittest.TestCase):
    
    # ========== Basic functionality tests ==========
    def test_set_get_roundtrip(self):
        """Test basic set and get of JSON data."""
        cache = RedisCache(client=FakeRedis())
        cache.set_json('demo', {'ok': True}, ttl=30)
        self.assertEqual(cache.get_json('demo'), {'ok': True})
    
    def test_get_nonexistent_key(self):
        """Test that getting a non-existent key returns None."""
        cache = RedisCache(client=FakeRedis())
        result = cache.get_json('does_not_exist')
        self.assertIsNone(result)
    
    def test_set_returns_true_on_success(self):
        """Test that set_json returns True when successful."""
        cache = RedisCache(client=FakeRedis())
        result = cache.set_json('key', {'data': 'value'})
        self.assertTrue(result)
    
    def test_delete_existing_key(self):
        """Test deleting an existing key removes it from cache."""
        cache = RedisCache(client=FakeRedis())
        cache.set_json('key_to_delete', {'data': 'value'})
        self.assertIsNotNone(cache.get_json('key_to_delete'))
        
        # Delete the key
        result = cache.delete('key_to_delete')
        self.assertTrue(result)
        
        # Verify it's gone
        self.assertIsNone(cache.get_json('key_to_delete'))
    
    def test_delete_nonexistent_key(self):
        """Test deleting a non-existent key returns False (gracefully)."""
        cache = RedisCache(client=FakeRedis())
        result = cache.delete('does_not_exist')
        self.assertFalse(result)
    
    # ========== TTL tests ==========
    def test_ttl_is_respected(self):
        """Test that custom TTL is stored properly."""
        fake_redis = FakeRedis()
        cache = RedisCache(client=fake_redis)
        
        # Set with custom TTL
        cache.set_json('ttl_key', {'data': 'value'}, ttl=120)
        
        # Verify the TTL was set
        self.assertEqual(fake_redis.ttls.get('ttl_key'), 120)
    
    def test_default_ttl_used_when_none_provided(self):
        """Test that default TTL (300s) is used when no TTL is specified."""
        fake_redis = FakeRedis()
        cache = RedisCache(client=fake_redis, default_ttl=300)
        
        cache.set_json('default_ttl_key', {'data': 'value'})
        
        # Should use default TTL of 300
        self.assertEqual(fake_redis.ttls.get('default_ttl_key'), 300)
    
    # ========== Complex data serialization tests ==========
    def test_complex_object_serialization(self):
        """Test caching complex nested objects."""
        cache = RedisCache(client=FakeRedis())
        
        complex_data = {
            'problems': [
                {'id': 1, 'title': 'Two Sum', 'difficulty': 'Easy'},
                {'id': 2, 'title': '3Sum', 'difficulty': 'Medium'}
            ],
            'metadata': {
                'total': 2,
                'hasMore': False
            }
        }
        
        cache.set_json('problems_list', complex_data)
        retrieved = cache.get_json('problems_list')
        
        self.assertEqual(retrieved, complex_data)
        self.assertEqual(retrieved['problems'][0]['title'], 'Two Sum')
    
    def test_datetime_serialization(self):
        """Test that datetime objects are serialized with default=str."""
        cache = RedisCache(client=FakeRedis())
        now = datetime.now()
        
        data = {
            'created_at': now,
            'message': 'Test message'
        }
        
        # Should not raise an exception even with datetime
        result = cache.set_json('datetime_key', data)
        self.assertTrue(result)
        
        retrieved = cache.get_json('datetime_key')
        # datetime is converted to string during serialization
        self.assertEqual(retrieved['message'], 'Test message')
        self.assertIsNotNone(retrieved['created_at'])
    
    def test_empty_dict_and_list(self):
        """Test caching empty data structures."""
        cache = RedisCache(client=FakeRedis())
        
        cache.set_json('empty_dict', {})
        cache.set_json('empty_list', [])
        
        self.assertEqual(cache.get_json('empty_dict'), {})
        self.assertEqual(cache.get_json('empty_list'), [])
    
    # ========== Error handling and graceful degradation ==========
    def test_cache_disabled_when_client_none(self):
        """Test that cache gracefully handles None client."""
        cache = RedisCache(client=None)
        
        # Should be disabled
        self.assertFalse(cache.enabled)
        
        # Operations should not crash, just return None/False
        self.assertIsNone(cache.get_json('any_key'))
        self.assertFalse(cache.set_json('any_key', {'data': 'value'}))
        self.assertFalse(cache.delete('any_key'))
    
    def test_empty_key_handling(self):
        """Test that empty/None keys are handled gracefully."""
        cache = RedisCache(client=FakeRedis())
        
        # Empty string key
        self.assertFalse(cache.set_json('', {'data': 'value'}))
        self.assertIsNone(cache.get_json(''))
        self.assertFalse(cache.delete(''))
        
        # None key
        self.assertFalse(cache.set_json(None, {'data': 'value'}))
        self.assertIsNone(cache.get_json(None))
        self.assertFalse(cache.delete(None))
    
    def test_set_operation_failure_disables_cache(self):
        """Test that a failed set operation disables the cache."""
        fake_redis = FakeRedis(fail_on_operation='set')
        cache = RedisCache(client=fake_redis)
        
        # Initially enabled
        self.assertTrue(cache.enabled)
        
        # Attempt set, which will fail
        result = cache.set_json('key', {'data': 'value'})
        
        # Should return False and disable cache
        self.assertFalse(result)
        self.assertFalse(cache.enabled)
    
    def test_get_operation_failure_disables_cache(self):
        """Test that a failed get operation disables the cache."""
        fake_redis = FakeRedis(fail_on_operation='get')
        cache = RedisCache(client=fake_redis)
        
        # Initially enabled
        self.assertTrue(cache.enabled)
        
        # Attempt get, which will fail
        result = cache.get_json('key')
        
        # Should return None and disable cache
        self.assertIsNone(result)
        self.assertFalse(cache.enabled)
    
    def test_delete_operation_failure_disables_cache(self):
        """Test that a failed delete operation disables the cache."""
        fake_redis = FakeRedis(fail_on_operation='delete')
        cache = RedisCache(client=fake_redis)
        
        # Initially enabled
        self.assertTrue(cache.enabled)
        
        # Attempt delete, which will fail
        result = cache.delete('key')
        
        # Should return False and disable cache
        self.assertFalse(result)
        self.assertFalse(cache.enabled)
    
    def test_ping_failure_disables_cache_on_init(self):
        """Test that failed ping on init disables the cache."""
        fake_redis = FakeRedis(fail_on_operation='ping')
        cache = RedisCache(client=fake_redis)
        
        # Should be disabled because ping failed
        self.assertFalse(cache.enabled)
    
    # ========== Multiple key operations ==========
    def test_multiple_keys_independent(self):
        """Test that multiple cached keys are independent."""
        cache = RedisCache(client=FakeRedis())
        
        cache.set_json('key1', {'value': 1})
        cache.set_json('key2', {'value': 2})
        cache.set_json('key3', {'value': 3})
        
        # Each key should have its own data
        self.assertEqual(cache.get_json('key1')['value'], 1)
        self.assertEqual(cache.get_json('key2')['value'], 2)
        self.assertEqual(cache.get_json('key3')['value'], 3)
        
        # Deleting one shouldn't affect others
        cache.delete('key2')
        self.assertEqual(cache.get_json('key1')['value'], 1)
        self.assertIsNone(cache.get_json('key2'))
        self.assertEqual(cache.get_json('key3')['value'], 3)
    
    def test_overwrite_existing_key(self):
        """Test that setting an existing key overwrites the old value."""
        cache = RedisCache(client=FakeRedis())
        
        cache.set_json('mutable_key', {'version': 1})
        self.assertEqual(cache.get_json('mutable_key')['version'], 1)
        
        # Overwrite with new data
        cache.set_json('mutable_key', {'version': 2})
        self.assertEqual(cache.get_json('mutable_key')['version'], 2)
    
    # ========== LeetCode-like scenario tests ==========
    def test_cache_problems_list(self):
        """Test caching a LeetCode problems list response."""
        cache = RedisCache(client=FakeRedis())
        
        problems_response = {
            'questions': [
                {'questionFrontendId': '1', 'title': 'Two Sum', 'difficulty': 'Easy'},
                {'questionFrontendId': '2', 'title': '3Sum', 'difficulty': 'Medium'},
            ],
            'hasMore': True
        }
        
        cache.set_json('leetcode:problems:skip=0:limit=15', problems_response, ttl=600)
        retrieved = cache.get_json('leetcode:problems:skip=0:limit=15')
        
        self.assertEqual(len(retrieved['questions']), 2)
        self.assertTrue(retrieved['hasMore'])
    
    def test_cache_conversation_list(self):
        """Test caching user conversations."""
        cache = RedisCache(client=FakeRedis())
        
        conversations = [
            {'id': 1, 'problem_id': 100, 'created_at': '2026-01-01T10:00:00'},
            {'id': 2, 'problem_id': 200, 'created_at': '2026-01-02T10:00:00'},
        ]
        
        cache.set_json('conversations:user:42', conversations, ttl=600)
        retrieved = cache.get_json('conversations:user:42')
        
        self.assertEqual(len(retrieved), 2)
        self.assertEqual(retrieved[0]['problem_id'], 100)
    
    def test_cache_invalidation_pattern(self):
        """Test the cache invalidation pattern used in the app."""
        cache = RedisCache(client=FakeRedis())
        user_id = 42
        conversation_id = 5
        
        # Cache some data
        cache.set_json(f'conversations:user:{user_id}', [{'id': conversation_id}])
        cache.set_json(f'conversation:{conversation_id}', {'id': conversation_id})
        cache.set_json(f'messages:conversation:{conversation_id}:user:{user_id}', [])
        
        # Verify cached
        self.assertIsNotNone(cache.get_json(f'conversations:user:{user_id}'))
        
        # Invalidate (as done in delete route)
        cache.delete(f'conversation:{conversation_id}')
        cache.delete(f'conversations:user:{user_id}')
        cache.delete(f'messages:conversation:{conversation_id}:user:{user_id}')
        
        # Verify all cleared
        self.assertIsNone(cache.get_json(f'conversation:{conversation_id}'))
        self.assertIsNone(cache.get_json(f'conversations:user:{user_id}'))
        self.assertIsNone(cache.get_json(f'messages:conversation:{conversation_id}:user:{user_id}'))


if __name__ == '__main__':
    unittest.main()
